[package]
name = "synforge-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
diesel.workspace = true
idna.workspace = true
rkyv.workspace = true
serde.workspace = true
serde_json.workspace = true
slug.workspace = true
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa.workspace = true
uuid.workspace = true
