[package]
name = "synforge-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "daemon"
path = "src/main.rs"

[[bin]]
name = "openapi-export"
path = "src/bin/openapi-export.rs"

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
axum.workspace = true
axum-helmet.workspace = true
base64.workspace = true
delegate.workspace = true
futures-util.workspace = true
helmet-core.workspace = true
serde.workspace = true
serde_json.workspace = true
strict-path.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
uuid.workspace = true
synforge-core = { path = "../../../libs/rust/core" }
synforge-database = { path = "../../../libs/rust/database" }
synforge-git-sync = { path = "../../../libs/rust/git-sync" }
synforge-publish = { path = "../../../libs/rust/publish" }
synforge-state = { path = "../../../libs/rust/state" }
synforge-worker-host = { path = "../../../libs/rust/worker-host" }
