[package]
name = "synforge-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "daemon"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
synforge-core = { path = "../../../libs/rust/core" }
synforge-orchestrator = { path = "../../../libs/rust/orchestrator" }
synforge-serve = { path = "../../../libs/rust/serve" }
