[package]
name = "synforge-orchestrator"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
async-trait.workspace = true
bollard.workspace = true
dashmap = "6.1"
futures-util.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true
synforge-core = { path = "../core" }
synforge-runtime = { path = "../runtime" }
synforge-store = { path = "../store" }
