[package]
name = "synforge-orchestrator"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
async-trait.workspace = true
bincode.workspace = true
bigdecimal.workspace = true
bollard.workspace = true
bytes.workspace = true
dashmap = "6.1"
diesel.workspace = true
diesel_migrations.workspace = true
futures-util.workspace = true
notify.workspace = true
reqwest.workspace = true
rand_core.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yml.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true
synforge-core = { path = "../core" }
