[package]
name = "synforge-database"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
async-trait.workspace = true
bigdecimal.workspace = true
diesel.workspace = true
diesel-async.workspace = true
diesel_migrations.workspace = true
futures-util.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
synforge-core = { path = "../core" }
time.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
