use utoipa::openapi::security::{ApiKey, ApiKeyValue, Http, HttpAuthScheme, SecurityScheme};
use utoipa::{Modify, OpenApi};

use super::{
    artifacts, cache, config, hardware, jobs, logs, packages, repo, session, setup, signing, sync,
    users,
};

pub(crate) struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "session_auth",
            SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::new("synforge_session"))),
        );
        components.add_security_scheme(
            "basic_auth",
            SecurityScheme::Http(Http::new(HttpAuthScheme::Basic)),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Synforge API",
        version = "v1",
        description = "Daemon API for package orchestration, logs, repository management, setup, and user administration. `/api/v1` uses a signed session cookie for the WebUI. `/repo` uses HTTP Basic Auth for package consumers."
    ),
    paths(
        packages::list_packages,
        packages::get_package,
        packages::create_package,
        packages::update_package,
        packages::delete_package,
        packages::list_mock_chroots,
        packages::browse_repository,
        packages::get_package_builds,
        packages::trigger_rebuild,
        packages::trigger_refresh,
        packages::trigger_refresh_all_packages,
        packages::get_refresh_all_packages_progress,
        packages::trigger_target_rebuild,
        packages::trigger_target_refresh,
        sync::list_sync_operations,
        sync::list_sync_batches,
        sync::get_sync_batch,
        sync::get_sync_operation,
        sync::retry_sync_operation,
        sync::cancel_sync_operation,
        sync::list_package_sync_operations,
        sync::get_sync_metrics,
        sync::get_sync_timeseries,
        sync::get_sync_schedule,
        cache::get_cache_stats,
        hardware::get_server_hardware,
        jobs::list_jobs,
        jobs::list_job_usage,
        jobs::get_jobs_timeseries,
        jobs::get_job,
        jobs::get_job_usage,
        jobs::kill_job,
        jobs::retry_job,
        artifacts::list_job_artifacts,
        artifacts::get_job_artifact_meta,
        jobs::delete_job,
        jobs::prune_failed_jobs,
        logs::get_job_log_manifest,
        logs::stream_job_logs,
        logs::get_sync_log_manifest,
        logs::stream_sync_logs,
        artifacts::download_job_artifact,
        repo::get_repo_inventory,
        repo::get_repo_summary,
        repo::get_repo_setup_info,
        signing::get_repo_signing_status,
        signing::get_repo_signing_reconcile_progress,
        signing::export_repo_signing_key,
        signing::export_repo_signing_public_key,
        signing::generate_repo_signing_key,
        signing::update_repo_signing_config,
        signing::import_repo_signing_key,
        signing::remove_repo_signing_key,
        signing::test_repo_signing,
        config::get_effective_config,
        config::get_config_schema,
        config::update_runtime_settings,
        setup::get_setup_status,
        setup::initialize_setup,
        session::login_session,
        session::logout_session,
        session::get_session,
        users::list_users,
        users::create_user,
        users::update_user,
        users::change_user_password,
        users::delete_user,
        users::get_user_metrics
    ),
    components(
        schemas(
            synforge_core::api::ApiError,
            synforge_core::api::BrowseRepositoryRequest,
            synforge_core::api::BrowseRepositoryResponse,
            synforge_core::api::BuildJobListResponse,
            synforge_core::api::BuildJobResponse,
            synforge_core::api::ChangePasswordRequest,
            synforge_core::api::ConfigFieldDescriptor,
            synforge_core::api::ConfigFieldType,
            synforge_core::api::ConfigSchemaResponse,
            synforge_core::api::CreatePackageRequest,
            synforge_core::api::CreateUserRequest,
            synforge_core::api::EffectiveConfigDto,
            synforge_core::api::EffectiveConfigView,
            synforge_core::api::JobArtifactListResponse,
            synforge_core::api::JobArtifactMetaResponse,
            synforge_core::api::JobResourceUsageSample,
            synforge_core::api::JobResourceUsageListResponse,
            synforge_core::api::JobResourceUsageResponse,
            synforge_core::api::LogManifestResponse,
            synforge_core::api::LogSource,
            synforge_core::api::LogSourceType,
            synforge_core::api::MockChrootListResponse,
            synforge_core::api::PackageActionDisposition,
            synforge_core::api::PackageActionResponse,
            synforge_core::api::PackageActionTargetResult,
            synforge_core::api::RefreshAllPackagesState,
            synforge_core::api::RefreshAllPackagesProgressView,
            synforge_core::api::RefreshAllPackagesProgressResponse,
            synforge_core::api::RefreshAllPackagesResponse,
            synforge_core::api::PackageBuildHistoryResponse,
            synforge_core::api::PackageBuildInventoryEntry,
            synforge_core::api::PackageListResponse,
            synforge_core::api::PackageResponse,
            synforge_core::api::PageInfo,
            synforge_core::api::PaginationQuery,
            synforge_core::api::PruneJobsResponse,
            synforge_core::api::RefreshRequest,
            synforge_core::api::RebuildRequest,
            synforge_core::api::RepoSigningStatusResponse,
            synforge_core::api::RepoSigningStatusView,
            synforge_core::api::RepoSigningReconcileMode,
            synforge_core::api::RepoSigningReconcileState,
            synforge_core::api::RepoSigningReconcileProgressView,
            synforge_core::api::RepoSigningReconcileProgressResponse,
            synforge_core::api::UpdateRepoSigningConfigRequest,
            synforge_core::api::GenerateRepoSigningKeyResponse,
            synforge_core::api::ImportRepoSigningKeyRequest,
            synforge_core::api::ImportRepoSigningKeyResponse,
            synforge_core::api::TestRepoSigningResponse,
            synforge_core::api::ExportRepoSigningKeyResponse,
            synforge_core::api::ExportRepoSigningPublicKeyResponse,
            synforge_core::api::RepoInventoryQuery,
            synforge_core::api::RepoInventoryResponse,
            synforge_core::api::RepoSetupInfoResponse,
            synforge_core::api::RepoSummaryResponse,
            synforge_core::api::RepoTargetSummary,
            synforge_core::api::SessionLoginRequest,
            synforge_core::api::SessionResponse,
            synforge_core::api::SyncOperationListQuery,
            synforge_core::api::PackageSyncOperationListQuery,
            synforge_core::api::SyncOperationListResponse,
            synforge_core::api::SyncBatchDetailResponse,
            synforge_core::api::SyncBatchListResponse,
            synforge_core::api::SyncEnqueueResponse,
            synforge_core::api::SyncOperationDetailResponse,
            synforge_core::api::SyncMetricsResponse,
            synforge_core::api::SyncScheduleEntry,
            synforge_core::api::SyncScheduleQuery,
            synforge_core::api::SyncScheduleResponse,
            synforge_core::api::TimeSeriesQuery,
            synforge_core::api::TimeSeriesPoint,
            synforge_core::api::TimeSeriesResponse,
            synforge_core::api::MockChrootCacheStats,
            synforge_core::api::GitMirrorCacheStats,
            synforge_core::api::CacheStatsResponse,
            synforge_core::api::ServerHardwareResponse,
            synforge_core::api::SetupAdminRequest,
            synforge_core::api::SetupInitializeRequest,
            synforge_core::api::SetupStatusResponse,
            synforge_core::api::UpdatePackageRequest,
            synforge_core::api::UpdateRuntimeSettingsRequest,
            synforge_core::api::UpdateUserRequest,
            synforge_core::api::JobListQuery,
            synforge_core::api::JobListScope,
            synforge_core::api::UserListResponse,
            synforge_core::api::UserMetricsResponse,
            synforge_core::api::UserResponse,
            synforge_core::model::ArtifactKind,
            synforge_core::model::ArtifactSigningStatus,
            synforge_core::model::BuildArtifact,
            synforge_core::model::BuildJob,
            synforge_core::model::BuildStatus,
            synforge_core::model::BuildTrigger,
            synforge_core::model::PackageRuntimeState,
            synforge_core::model::PublishedRepoFile,
            synforge_core::model::UserAccount,
            synforge_core::model::UserPermission,
            synforge_core::model::UserRepoMetrics,
            synforge_core::package::BuildEnvVar,
            synforge_core::package::PackageDefinition,
            synforge_core::package::SpecSource,
            synforge_core::sync::SyncOperation,
            synforge_core::sync::SyncBatch,
            synforge_core::sync::SyncBatchStatus,
            synforge_core::sync::SyncOperationEvent,
            synforge_core::sync::SyncEventLevel,
            synforge_core::sync::SyncStage,
            synforge_core::sync::SyncStatus,
            synforge_core::sync::SyncTriggerType
        )
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "Setup", description = "First-run setup and bootstrap"),
        (name = "Session", description = "WebUI session management"),
        (name = "Packages", description = "Package definitions and package-level operations"),
        (name = "Jobs", description = "Build job lifecycle and artifacts"),
        (name = "Sync", description = "Sync operation history and health metrics"),
        (name = "Logs", description = "Per-job log source discovery and SSE log streaming"),
        (name = "Repository", description = "Managed repository inventory and source browsing"),
        (name = "Signing", description = "Optional repository metadata signing key and status management"),
        (name = "Statistics", description = "System and cache telemetry endpoints"),
        (name = "Settings", description = "Daemon configuration schema and runtime updates"),
        (name = "Users", description = "Administrative user and permissions management")
    )
)]
pub struct ApiDoc;
