/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSigningRouteImport } from './routes/_authed/signing'
import { Route as AuthedStatisticsRouteImport } from './routes/_authed/statistics'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedJobsIndexRouteImport } from './routes/_authed/jobs/index'
import { Route as AuthedJobsViewRouteImport } from './routes/_authed/jobs/view'
import { Route as AuthedPackagesIndexRouteImport } from './routes/_authed/packages/index'
import { Route as AuthedPackagesViewRouteImport } from './routes/_authed/packages/view'
import { Route as AuthedRepositoryIndexRouteImport } from './routes/_authed/repository/index'
import { Route as AuthedRepositoryUseRouteImport } from './routes/_authed/repository/use'
import { Route as AuthedSyncsIndexRouteImport } from './routes/_authed/syncs/index'
import { Route as AuthedSyncsBatchRouteImport } from './routes/_authed/syncs/batch'
import { Route as AuthedSyncsViewRouteImport } from './routes/_authed/syncs/view'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSigningRoute = AuthedSigningRouteImport.update({
  id: '/signing',
  path: '/signing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStatisticsRoute = AuthedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsIndexRoute = AuthedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsViewRoute = AuthedJobsViewRouteImport.update({
  id: '/jobs/view',
  path: '/jobs/view',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPackagesIndexRoute = AuthedPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPackagesViewRoute = AuthedPackagesViewRouteImport.update({
  id: '/packages/view',
  path: '/packages/view',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRepositoryIndexRoute = AuthedRepositoryIndexRouteImport.update({
  id: '/repository/',
  path: '/repository/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRepositoryUseRoute = AuthedRepositoryUseRouteImport.update({
  id: '/repository/use',
  path: '/repository/use',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSyncsIndexRoute = AuthedSyncsIndexRouteImport.update({
  id: '/syncs/',
  path: '/syncs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSyncsBatchRoute = AuthedSyncsBatchRouteImport.update({
  id: '/syncs/batch',
  path: '/syncs/batch',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSyncsViewRoute = AuthedSyncsViewRouteImport.update({
  id: '/syncs/view',
  path: '/syncs/view',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/settings': typeof AuthedSettingsRoute
  '/signing': typeof AuthedSigningRoute
  '/statistics': typeof AuthedStatisticsRoute
  '/users': typeof AuthedUsersRoute
  '/jobs/view': typeof AuthedJobsViewRoute
  '/packages/view': typeof AuthedPackagesViewRoute
  '/repository/use': typeof AuthedRepositoryUseRoute
  '/syncs/batch': typeof AuthedSyncsBatchRoute
  '/syncs/view': typeof AuthedSyncsViewRoute
  '/jobs/': typeof AuthedJobsIndexRoute
  '/packages/': typeof AuthedPackagesIndexRoute
  '/repository/': typeof AuthedRepositoryIndexRoute
  '/syncs/': typeof AuthedSyncsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/settings': typeof AuthedSettingsRoute
  '/signing': typeof AuthedSigningRoute
  '/statistics': typeof AuthedStatisticsRoute
  '/users': typeof AuthedUsersRoute
  '/': typeof AuthedIndexRoute
  '/jobs/view': typeof AuthedJobsViewRoute
  '/packages/view': typeof AuthedPackagesViewRoute
  '/repository/use': typeof AuthedRepositoryUseRoute
  '/syncs/batch': typeof AuthedSyncsBatchRoute
  '/syncs/view': typeof AuthedSyncsViewRoute
  '/jobs': typeof AuthedJobsIndexRoute
  '/packages': typeof AuthedPackagesIndexRoute
  '/repository': typeof AuthedRepositoryIndexRoute
  '/syncs': typeof AuthedSyncsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/signing': typeof AuthedSigningRoute
  '/_authed/statistics': typeof AuthedStatisticsRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/jobs/view': typeof AuthedJobsViewRoute
  '/_authed/packages/view': typeof AuthedPackagesViewRoute
  '/_authed/repository/use': typeof AuthedRepositoryUseRoute
  '/_authed/syncs/batch': typeof AuthedSyncsBatchRoute
  '/_authed/syncs/view': typeof AuthedSyncsViewRoute
  '/_authed/jobs/': typeof AuthedJobsIndexRoute
  '/_authed/packages/': typeof AuthedPackagesIndexRoute
  '/_authed/repository/': typeof AuthedRepositoryIndexRoute
  '/_authed/syncs/': typeof AuthedSyncsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/settings'
    | '/signing'
    | '/statistics'
    | '/users'
    | '/jobs/view'
    | '/packages/view'
    | '/repository/use'
    | '/syncs/batch'
    | '/syncs/view'
    | '/jobs/'
    | '/packages/'
    | '/repository/'
    | '/syncs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/settings'
    | '/signing'
    | '/statistics'
    | '/users'
    | '/'
    | '/jobs/view'
    | '/packages/view'
    | '/repository/use'
    | '/syncs/batch'
    | '/syncs/view'
    | '/jobs'
    | '/packages'
    | '/repository'
    | '/syncs'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/setup'
    | '/_authed/settings'
    | '/_authed/signing'
    | '/_authed/statistics'
    | '/_authed/users'
    | '/_authed/'
    | '/_authed/jobs/view'
    | '/_authed/packages/view'
    | '/_authed/repository/use'
    | '/_authed/syncs/batch'
    | '/_authed/syncs/view'
    | '/_authed/jobs/'
    | '/_authed/packages/'
    | '/_authed/repository/'
    | '/_authed/syncs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/signing': {
      id: '/_authed/signing'
      path: '/signing'
      fullPath: '/signing'
      preLoaderRoute: typeof AuthedSigningRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/statistics': {
      id: '/_authed/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthedStatisticsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/': {
      id: '/_authed/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthedJobsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/view': {
      id: '/_authed/jobs/view'
      path: '/jobs/view'
      fullPath: '/jobs/view'
      preLoaderRoute: typeof AuthedJobsViewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/packages/': {
      id: '/_authed/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof AuthedPackagesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/packages/view': {
      id: '/_authed/packages/view'
      path: '/packages/view'
      fullPath: '/packages/view'
      preLoaderRoute: typeof AuthedPackagesViewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/repository/': {
      id: '/_authed/repository/'
      path: '/repository'
      fullPath: '/repository/'
      preLoaderRoute: typeof AuthedRepositoryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/repository/use': {
      id: '/_authed/repository/use'
      path: '/repository/use'
      fullPath: '/repository/use'
      preLoaderRoute: typeof AuthedRepositoryUseRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/syncs/': {
      id: '/_authed/syncs/'
      path: '/syncs'
      fullPath: '/syncs/'
      preLoaderRoute: typeof AuthedSyncsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/syncs/batch': {
      id: '/_authed/syncs/batch'
      path: '/syncs/batch'
      fullPath: '/syncs/batch'
      preLoaderRoute: typeof AuthedSyncsBatchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/syncs/view': {
      id: '/_authed/syncs/view'
      path: '/syncs/view'
      fullPath: '/syncs/view'
      preLoaderRoute: typeof AuthedSyncsViewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSigningRoute: typeof AuthedSigningRoute
  AuthedStatisticsRoute: typeof AuthedStatisticsRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedJobsViewRoute: typeof AuthedJobsViewRoute
  AuthedPackagesViewRoute: typeof AuthedPackagesViewRoute
  AuthedRepositoryUseRoute: typeof AuthedRepositoryUseRoute
  AuthedSyncsBatchRoute: typeof AuthedSyncsBatchRoute
  AuthedSyncsViewRoute: typeof AuthedSyncsViewRoute
  AuthedJobsIndexRoute: typeof AuthedJobsIndexRoute
  AuthedPackagesIndexRoute: typeof AuthedPackagesIndexRoute
  AuthedRepositoryIndexRoute: typeof AuthedRepositoryIndexRoute
  AuthedSyncsIndexRoute: typeof AuthedSyncsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSigningRoute: AuthedSigningRoute,
  AuthedStatisticsRoute: AuthedStatisticsRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedJobsViewRoute: AuthedJobsViewRoute,
  AuthedPackagesViewRoute: AuthedPackagesViewRoute,
  AuthedRepositoryUseRoute: AuthedRepositoryUseRoute,
  AuthedSyncsBatchRoute: AuthedSyncsBatchRoute,
  AuthedSyncsViewRoute: AuthedSyncsViewRoute,
  AuthedJobsIndexRoute: AuthedJobsIndexRoute,
  AuthedPackagesIndexRoute: AuthedPackagesIndexRoute,
  AuthedRepositoryIndexRoute: AuthedRepositoryIndexRoute,
  AuthedSyncsIndexRoute: AuthedSyncsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
